# Generated by Django 3.1.1 on 2020-09-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(choices=[('ArepaHuevo', 'Arepahuevo'), ('Carimanola', 'Carimanola'), ('Empanada', 'Empanada'), ('Salchipapa', 'Salchipapa'), ('Bollo', 'Bollo')], max_length=20)),
                ('Imagen', models.ImageField(upload_to='shop/media')),
                ('Tamano', models.CharField(blank=True, choices=[('Pequeno', 'Pequeno'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=10, null=True)),
                ('Disponible', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=5, null=True)),
                ('Crated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comida',
                'verbose_name_plural': 'Comidas',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Nombre', models.CharField(max_length=20)),
                ('Apellido', models.CharField(max_length=20)),
                ('TipoDoc', models.CharField(max_length=4)),
                ('NumeroDoc', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('CorreoElectronico', models.EmailField(max_length=30)),
                ('TelefonoCelular', models.TextField(max_length=10)),
                ('Usuario', models.CharField(max_length=10)),
                ('Passwd', models.CharField(max_length=12)),
                ('Crated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
