# Generated by Django 3.1.1 on 2020-09-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='PrecioU',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='comida',
            name='Disponible',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='comida',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='shop/media'),
        ),
        migrations.AlterField(
            model_name='comida',
            name='Tamano',
            field=models.CharField(choices=[('Pequeno', 'Pequeno'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='comida',
            name='Tipo',
            field=models.CharField(choices=[('ArepaHuevo', 'Arepahuevo'), ('Carimanola', 'Carimanola'), ('Empanada', 'Empanada'), ('Salchipapa', 'Salchipapa'), ('Bollo', 'Bollo')], max_length=20, null=True),
        ),
    ]
