# Generated by Django 3.1.1 on 2020-09-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200911_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArepadeHuevo',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Imagen', models.ImageField(null=True, upload_to='shop/media')),
                ('Tamano', models.CharField(choices=[('Pequeno', 'Pequeno'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=10, null=True)),
                ('PrecioU', models.CharField(max_length=5, null=True)),
                ('Disponible', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=5, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ArepadeHuevo',
                'verbose_name_plural': 'ArepadeHuevos',
            },
        ),
        migrations.CreateModel(
            name='Bollo',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Imagen', models.ImageField(null=True, upload_to='shop/media')),
                ('Tamano', models.CharField(choices=[('Pequeno', 'Pequeno'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=10, null=True)),
                ('PrecioU', models.CharField(max_length=5, null=True)),
                ('Disponible', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=5, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bollo',
                'verbose_name_plural': 'Bollos',
            },
        ),
        migrations.CreateModel(
            name='Carimanola',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Imagen', models.ImageField(null=True, upload_to='shop/media')),
                ('Tamano', models.CharField(choices=[('Pequeno', 'Pequeno'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=10, null=True)),
                ('PrecioU', models.CharField(max_length=5, null=True)),
                ('Disponible', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=5, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carimanola',
                'verbose_name_plural': 'Carimanolas',
            },
        ),
        migrations.CreateModel(
            name='Empanada',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Imagen', models.ImageField(null=True, upload_to='shop/media')),
                ('Tamano', models.CharField(choices=[('Pequeno', 'Pequeno'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=10, null=True)),
                ('PrecioU', models.CharField(max_length=5, null=True)),
                ('Disponible', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=5, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empanada',
                'verbose_name_plural': 'Empanadas',
            },
        ),
        migrations.CreateModel(
            name='Salchipapa',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Imagen', models.ImageField(null=True, upload_to='shop/media')),
                ('Tamano', models.CharField(choices=[('Pequeno', 'Pequeno'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=10, null=True)),
                ('PrecioU', models.CharField(max_length=5, null=True)),
                ('Disponible', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=5, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Salchipapa',
                'verbose_name_plural': 'Salchipapas',
            },
        ),
        migrations.DeleteModel(
            name='Comida',
        ),
    ]
