# Generated by Django 3.1.1 on 2020-09-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200914_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bollo',
            name='name',
            field=models.CharField(default='Bollo', max_length=20),
        ),
        migrations.AlterField(
            model_name='carimanola',
            name='name',
            field=models.CharField(default='Carimanola', max_length=20),
        ),
        migrations.AlterField(
            model_name='empanada',
            name='name',
            field=models.CharField(default='Empanada', max_length=20),
        ),
        migrations.AlterField(
            model_name='salchipapa',
            name='name',
            field=models.CharField(default='Salchipapa', max_length=20),
        ),
    ]
